### ISSUE TITLE
new release with find instead of scan (and AoC is so much fun with Possum)

### ISSUE THREAD

**Issue by pietroppeter** [mulias/possum_parser_language#17]
hi @mulias I am using possum for the parsing part of this year Advent of Code and I am having really fun!

I have to say among the various blog articles and documentation overview and AoC examples, learning this has been rather straightforward until now.

the only thing I tripped on today is the fact that `scan` has been renamed to `find` but the last release still uses `scan` (looking for `find` in the repo made me understand this).

Anyway today I am really proud of my solution for part2 (of day 3), the first day it required some advance possum pattern, I added a little explainer in my repo: https://github.com/pietroppeter/advent-of-code-2024/blob/main/03.md

**Comment by mulias** [comment]
Awesome, thanks so much for the feedback @pietroppeter!

Thank you for catching that discrepancy, I should have made a new release when I updated the tutorial. The change from `scan` to `find` is now in [v0.11.0](https://github.com/mulias/possum_parser_language/releases/tag/v0.11.0). If you want to keep using your current version you should be able to run `possum --docs=stdlib` to view your built in functions from the command line. The docs are still hand written so it's always possible that will be incorrect, but I try :)

I love your write up, and it's particularly helpful for me to see how the json gets loaded in to Nim with jsony. I think that using the same object shape for the three kinds of values makes a lot of sense for day 3, but I'm curious if there will be any later puzzles where the data is complex enough that you'll want to use ADTs ([object variants](https://nim-lang.org/docs/manual.html#types-object-variants)?) and how that will work with possum and jsony.

**Comment by pietroppeter** [comment]
updated to v11.0 possum and my parser files!

thanks for feedback on the writeup. Yes, jsony makes it a very practical combo, I just have to define the type (and make sure that possum output agrees with it).

Also yes, I probably could have used object variants (indeed those are ADTs in Nim), but I went with a simpler route. Will use ADTs next time, they are [supported in jsony](https://github.com/treeform/jsony/tree/8d58f03fe92aa13ed2e5d471ed83cac5bfec1bd3?tab=readme-ov-file#full-support-for-case-variant-objects). By default you need to use the [`kind`](https://github.com/treeform/jsony/blob/8d58f03fe92aa13ed2e5d471ed83cac5bfec1bd3/tests/test_objects.nim#L205) field (convention in Nim) but you can also [rename](https://github.com/treeform/jsony/blob/8d58f03fe92aa13ed2e5d471ed83cac5bfec1bd3/tests/test_objects.nim#L164) it to something else with a `renameHook`.

closing this, since release fixed the official reason for the issue

**Comment by pietroppeter** [comment]
ah also very useful the hint about `--docs=stdlib` did not know about it, will definitely use it!
